# Generated by Django 6.0.2 on 2026-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('parentesco', models.CharField(choices=[('HIJO', 'Hijo/a'), ('PADRE', 'Padre/Madre'), ('PAREJA', 'Pareja'), ('HERMANO', 'Hermano/a')], max_length=10)),
                ('face_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
