# Generated by Django 6.0.2 on 2026-02-07 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_recuerdos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='face_id',
        ),
        migrations.AddField(
            model_name='familiar',
            name='biografia',
            field=models.TextField(blank=True, help_text='Notas históricas sobre este familiar'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RostroDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_recorte', models.ImageField(upload_to='rostros_permanentes/')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rostros', to='gestion_recuerdos.familiar')),
            ],
        ),
    ]
