# Generated by Django 6.0.2 on 2026-02-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_recuerdos', '0002_remove_familiar_apellido_remove_familiar_face_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='face_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('HIJO', 'Hijo/a'), ('PADRE', 'Padre/Madre'), ('PAREJA', 'Pareja'), ('HERMANO', 'Hermano/a')], max_length=10, null=True),
        ),
    ]
